language: objective-c
osx_image: xcode7
xcode_workspace: fh-ios-sdk.xcworkspace
xcode_scheme: Pods-FeedHenryTests
xcode_sdk: iphonesimulator

before_install:
    - gem install cocoapods obcd slather -N --no-rdoc --no-ri --no-document --quiet

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master
after_success: slather
